### PR TITLE
Initial commit of starwit-accounts-internal

### PR DESCRIPTION
**Pull request by DerCed**

### CODE REVIEW

**Review by witchpou — APPROVED** [review]

**Comment by flonix8** [comment]
What is the purpose of this Helm chart? As far as I understand, it is mostly a custom values file for the Keycloak chart.
Do you expect (or maybe have already encountered) any use cases for a separate helm chart?

**Comment by DerCed** [comment]
> What is the purpose of this Helm chart? As far as I understand, it is mostly a custom values file for the Keycloak chart. Do you expect (or maybe have already encountered) any use cases for a separate helm chart?

@flonix8  Theoretically, you could just use the helm install command from the bitnami chart. I used this approach however to document the values and how it is installed. If you have another option how we could package this, please let me know!

**Comment by flonix8** [comment]
@DerCed Anett and I have looked at Helmfile recently. It seems to solve (among others) exactly this problem: Templating and/or predefining the values for one or more existing Helm Charts without creating an umbrella chart.
I'd happily assist converting this into a Helmfile :)
If we need this asap, I'd say we merge it now and migrate later.

**Review by flonix8 — APPROVED** [review]

**Comment by DerCed** [comment]
> @DerCed Anett and I have looked at Helmfile recently. It seems to solve (among others) exactly this problem: Templating and/or predefining the values for one or more existing Helm Charts without creating an umbrella chart. I'd happily assist converting this into a Helmfile :) If we need this asap, I'd say we merge it now and migrate later.

Will do in https://dev.azure.com/starwit/Management/_backlogs/backlog/Management%20Team/Epics?workitem=680

**Pull request merged**
